exclude: |
  (?x)^(
      .*\{\{.*\}\}.*|     # Exclude any files with cookiecutter variables
      docs/site/.*|       # Exclude mkdocs compiled files
      \.history/.*|       # Exclude history files
      .*cache.*/.*|       # Exclude cache directories
      .*venv.*/.*|        # Exclude virtual environment directories
  )$
fail_fast: true
default_language_version:
  python: python3.13
default_install_hook_types:
  - pre-commit
  - commit-msg
repos:
  # Documentation: https://gatlenculp.github.io/gatlens-opinionated-template/precommit/

  # Security tools
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.28.0
    hooks:
      - id: gitleaks
        name: "security - Detect hardcoded secrets"

  # Code quality tools
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.1
    hooks:
      - id: ruff-format
        name: "python - Format with Ruff"
      - id: ruff
        args: ["--fix"]
        language_version: python3.13

  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.406
    hooks:
      - id: pyright
        name: "python - Check types"

  - repo: https://github.com/abravalheri/validate-pyproject
    rev: v0.24.1
    hooks:
      - id: validate-pyproject
        name: "python - Validate pyproject.toml"
        additional_dependencies: ["validate-pyproject-schema-store[all]"]

  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.34.1
    hooks:
      - id: check-github-workflows
        name: "github-actions - Validate gh workflow files"
        args: ["--verbose"]
      - id: check-taskfile
        name: "taskfile - Validate Task configuration"

  - repo: https://github.com/hukkin/mdformat
    rev: 0.7.22
    hooks:
      - id: mdformat
        name: "markdown - Format markdown"
        additional_dependencies:
          - mdformat-gfm
          - mdformat-ruff
          - mdformat-frontmatter
          - ruff

  - repo: https://github.com/mrtazz/checkmake.git
    rev: 0.2.2
    hooks:
      - id: checkmake
        name: "Makefile - Lint Makefile"

  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 3.5.0
    hooks:
      - id: sqlfluff-fix
        name: "sql - Attempts to fix rule violations"
        args: ["--dialect", "postgres"]

  - repo: https://github.com/shssoichiro/oxipng
    rev: v9.1.5
    hooks:
      - id: oxipng
        name: "images - Optimize PNG files"
        args: ["-o", "4", "--strip", "safe", "--alpha"]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-executables-have-shebangs
        name: "filesystem exec - Verify shebang presence"
      - id: check-shebang-scripts-are-executable
        name: "filesystem exec - Verify script permissions"
      - id: check-case-conflict
        name: "filesystem names - Check case sensitivity"
      - id: check-illegal-windows-names
        name: "filesystem names - Validate Windows filenames"
      - id: check-symlinks
        name: "filesystem symlink - Check symlink validity"
      - id: destroyed-symlinks
        name: "filesystem symlink - Detect broken symlinks"
      - id: check-merge-conflict
        name: "git - Detect conflict markers"
      - id: forbid-new-submodules
        name: "git - Prevent submodule creation"
      - id: no-commit-to-branch
        name: "git - Protect main branches"
        args: ["--branch", "main", "--branch", "master"]
      - id: check-added-large-files
        name: "git - Block large file commits"
        args: ["--maxkb=5000"]

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.9.1
    hooks:
      - id: commitizen
        stages: [commit-msg]
        name: "git - Validate commit message"